In [1]:
import numpy as np

In [2]:
# 1D Array - float Elements
npArray = np.ones(7)
npArray

array([1., 1., 1., 1., 1., 1., 1.])

In [3]:
# 2D array - We need to shape of array as tupple with 1st element of tupple 
# representing number of rows and second element as number of column
npArray = np.ones((2,3)) # Array with 2 rows and 3 columns
npArray

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
# 2D array - We need to shape of array as tupple with 1st element of tupple 
# representing number of rows and second element as number of column
npArray = np.ones((2,3), 'bool') # Array with 2 rows and 3 columns
npArray

array([[ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# 2D array - We need to shape of array as tupple with 1st element of tupple 
# representing number of rows and second element as number of column
npArray = np.ones((2,3), 'int') # Array with 2 rows and 3 columns
npArray

array([[1, 1, 1],
       [1, 1, 1]])

In [6]:
# 3D array
npArray = np.ones((2,3,3), 'bool') # Array with 2 rows and 3 columns
npArray

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [7]:
npArray = np.zeros((3,4), order='F')
npArray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
npArray = np.zeros(7)
npArray

array([0., 0., 0., 0., 0., 0., 0.])

In [9]:
# 2D Array with 3 rows and 4 columns and all elements as int
npArray = np.zeros((3,4), 'int')
npArray

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
# 3D Array with all elements in Boolean
npArray = np.zeros((2,3,4), 'bool')
npArray

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]])

In [11]:
# Array with 3 rows 4 columns and diagonal starting @ index 0.
npArray = np.eye(3,4,0, 'int') 
npArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [12]:
# Array with 3 rows and diagonal starting @ index 1.
npArray = np.eye(3,k=1,dtype='bool') 
npArray

array([[False,  True, False],
       [False, False,  True],
       [False, False, False]])

In [13]:
# NumPy Array with 1D array as argument
npArray = np.diag([1,2,3,4])
npArray

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
# NumPy Array with 2D array as argument
npArray = np.diag([[1,2,3], [4,5,6], [7,8,9]])
npArray

array([1, 5, 9])

In [16]:
# NumPy Array with 1D array as argument with diagonal starting at index 1
npArray = np.diag([1,2,3,4], k=1)
npArray

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [22]:
# Empty NumPy 1D Array with 4 elements
npArray = np.empty((4))
npArray

array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323])

In [24]:
# Empty NumPy 2D Array with 3 rows and 3 columns and integer elements 
npArray = np.empty((3,3), 'int')
npArray

array([[                   0, -1152912720391801969,                    6],
       [                   0,                    0,                    0],
       [                   0,                    0,                    3]])

In [26]:
# Creating 1D Array from arange() function
# np.arange(start, end, step, dtype='float64')
npArray = np.arange(1, 10, 2, dtype='int')
npArray

array([1, 3, 5, 7, 9])

In [28]:
# Empty Array using arange()
npArray = np.arange( 2, 2)
npArray

array([], dtype=int64)

In [32]:
# reshape(): converts 1D array into multidimensional array
arr_1D = np.arange(0,15, dtype='int') # creates 1D array with 15 elements
arr_2D = arr_1D.reshape(3,5) # created 2D array with 3 rows and 5 columns
arr_2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
# Create 3 D array from 1D array
arr_3D = np.reshape(arr_1D, (1,3,5))
arr_3D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [34]:
# ravel() L converts multi dimensional array into 1D array
arr_1D = arr_3D.ravel()
arr_1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
# transpose(): interchanges rows and columns of a matrix.
arr_2DT = arr_2D.transpose() # converts 3x5 array into 5x3 array.
arr_2DT

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])