In [1]:
import numpy as np

In [2]:
# rand() - Generating 1D array with 10 element
npArray = np.random.rand(10)
npArray

array([0.40294964, 0.54156907, 0.95505905, 0.95797353, 0.84789459,
       0.83114894, 0.26425322, 0.36972283, 0.18315424, 0.34390613])

In [3]:
# rand() - Generating 2D array with 3 rows and 4 columns
npArray = np.random.rand(3, 4)
npArray

array([[0.79011814, 0.67438543, 0.85717643, 0.49035314],
       [0.2538174 , 0.67465359, 0.84609358, 0.28868213],
       [0.7251408 , 0.74146801, 0.07928876, 0.65966774]])

In [4]:
# rand() - Generating 3D array
npArray = np.random.rand(2, 3, 4)
npArray

array([[[0.36901405, 0.29630357, 0.89716706, 0.88066347],
        [0.65294531, 0.52787692, 0.34108109, 0.33829834],
        [0.16945255, 0.92105959, 0.16731574, 0.74373693]],

       [[0.4738373 , 0.80278285, 0.47469206, 0.06841118],
        [0.38598055, 0.51065038, 0.46915624, 0.98841991],
        [0.39079833, 0.52674999, 0.42606409, 0.31763665]]])

In [5]:
# randn() - generating 1D array with 10 elements
npArray = np.random.randn(10)
npArray

array([-1.60839458,  0.40163407, -0.27674734, -0.42650954,  1.30109763,
        0.67785358,  0.70711838, -0.96556084,  0.54468467, -0.62752151])

In [6]:
# randn() - generating 2D array with 3 rows and 4 columns
npArray = np.random.randn(3, 4)
npArray

array([[ 0.55154427,  0.44443086,  2.24884829, -0.60290936],
       [-0.03071697, -0.27725378, -1.57754521, -0.22968449],
       [-0.43541253, -1.56107322,  1.20797895,  0.15834   ]])

In [7]:
# randn() - generating 3D Array
npArray = np.random.randn(2,3,4)
npArray

array([[[-0.21900942,  1.00096441, -1.2462665 ,  0.50739209],
        [ 0.23407204,  0.2951788 , -1.72703075, -0.03653191],
        [ 0.65837779,  0.97151303,  2.64841322,  0.02618502]],

       [[-1.75393823, -0.26579912,  0.43071926,  1.26324601],
        [-1.43048891, -0.40737261,  0.59526046, -0.39555748],
        [-0.23729094, -0.01326983, -1.78345976, -0.49350464]]])

In [8]:
# randint() - generating 1D array with 10 elements between 1 and 100
npArray = np.random.randint(1, 100, size=(10))
npArray

array([21, 16, 81, 44,  9, 26, 26, 15, 89, 52])

In [9]:
# randint() - generating 2D array with 3 rows and 4 columns nd elements between 1 and 100
npArray = np.random.randint(1, 100, size=(3, 4))
npArray

array([[36, 49, 47, 47],
       [ 3, 59, 45,  5],
       [42, 81, 58, 68]])

In [10]:
# randint() - generating 2D array with 3 rows and 4 columns nd elements between 1 and 100 with dtype as bool
npArray = np.random.randint(0, 2, size=(3, 4), dtype='bool')
npArray

array([[False,  True,  True,  True],
       [False,  True,  True,  True],
       [False, False, False, False]])

In [17]:
# seed()
np.random.seed(1)
npArray = np.random.randint(0, 10, (3,3))
npArray

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [18]:
# seed()
np.random.seed(1)
npArray = np.random.randint(0, 10, (9))
npArray

array([5, 8, 9, 5, 0, 0, 1, 7, 6])