In [1]:
import numpy as np
np.random.seed(1)
arr1 = np.random.randint(1, 20, (3, 3))
arr2 = np.random.randint(1, 20, (3, 3))
print(f"Array1\n{arr1}")
print()
print(f"Array2\n{arr2}")

Array1
[[ 6 12 13]
 [ 9 10 12]
 [ 6 16  1]]

Array2
[[17  2 13]
 [ 8 14  7]
 [19  6 19]]


In [2]:
# add()
arr_add = np.add(arr1, arr2)
arr_add

array([[23, 14, 26],
       [17, 24, 19],
       [25, 22, 20]])

In [3]:
# subtract()
arr_subtract = np.subtract(arr1, arr2)
arr_subtract

array([[-11,  10,   0],
       [  1,  -4,   5],
       [-13,  10, -18]])

In [4]:
# divide()
arr_divide = np.divide(arr1, arr2)
arr_divide

array([[0.35294118, 6.        , 1.        ],
       [1.125     , 0.71428571, 1.71428571],
       [0.31578947, 2.66666667, 0.05263158]])

In [5]:
# multiply()
arr_multiply = np.multiply(arr1, arr2)
arr_multiply

array([[102,  24, 169],
       [ 72, 140,  84],
       [114,  96,  19]])

In [6]:
# sqrt()
arr_sqrt = np.sqrt(arr1)
arr_sqrt

array([[2.44948974, 3.46410162, 3.60555128],
       [3.        , 3.16227766, 3.46410162],
       [2.44948974, 4.        , 1.        ]])

In [7]:
# square()
arr_square = np.square(arr1)
arr_square

array([[ 36, 144, 169],
       [ 81, 100, 144],
       [ 36, 256,   1]], dtype=int32)

In [8]:
# log()
arr_log = np.log(arr1)
arr_log

array([[1.79175947, 2.48490665, 2.56494936],
       [2.19722458, 2.30258509, 2.48490665],
       [1.79175947, 2.77258872, 0.        ]])

In [9]:
# log10()
arr_log10 = np.log10(arr1)
arr_log10

array([[0.77815125, 1.07918125, 1.11394335],
       [0.95424251, 1.        , 1.07918125],
       [0.77815125, 1.20411998, 0.        ]])

In [10]:
# around() with default numbers of decimals as 0
arr_around = np.around(np.sqrt(arr1))
arr_around

array([[2., 3., 4.],
       [3., 3., 3.],
       [2., 4., 1.]])

In [11]:
# around() with numbers of decimals as 2
arr_around = np.around(np.sqrt(arr1), decimals=2)
arr_around

array([[2.45, 3.46, 3.61],
       [3.  , 3.16, 3.46],
       [2.45, 4.  , 1.  ]])

In [12]:
# floor() with numbers of decimals as 2
arr_floor = np.floor(np.sqrt(arr1))
arr_floor

array([[2., 3., 3.],
       [3., 3., 3.],
       [2., 4., 1.]])

In [13]:
# ceil()
arr_ceil = np.ceil(np.sqrt(arr1))
arr_ceil

array([[3., 4., 4.],
       [3., 4., 4.],
       [3., 4., 1.]])

In [14]:
# nan_to_num()
arr_nan_to_num = np.nan_to_num(arr1)
arr_nan_to_num

array([[ 6, 12, 13],
       [ 9, 10, 12],
       [ 6, 16,  1]])

In [15]:
# maximum()
arr_maximum = np.maximum(arr1, arr2)
arr_maximum

array([[17, 12, 13],
       [ 9, 14, 12],
       [19, 16, 19]])