In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 13, 1).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
print(f"Shape - {arr.shape}")
print(f"Dimension - {arr.ndim}")
print(f"Size - {arr.size}")
print(f"Memory Usage - {arr.nbytes} bytes")

Shape - (3, 4)
Dimension - 2
Size - 12
Memory Usage - 48 bytes


In [4]:
# creating view of a numpy arrray
arr_view = arr[:, 0:3]
arr_view

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [5]:
# changing element at [0,0] of arr_view will also change value of element [0,0] in arr
print("Before changing arr_view")
print(f"arr_view[0,0] = {arr_view[0,0]}")
print(f"arr[0,0] = {arr[0,0]}")
print("="*30)
print("After changing arr_view")
arr_view[0,0] = 100
print(f"arr_view[0,0] = {arr_view[0,0]}")
print(f"arr[0,0] = {arr[0,0]}")

Before changing arr_view
arr_view[0,0] = 1
arr[0,0] = 1
After changing arr_view
arr_view[0,0] = 100
arr[0,0] = 100


In [7]:
    # creating copy of a numpy arrray
    arr_copy = arr[:, 0:3].copy()
    arr_copy

array([[100,   2,   3],
       [  5,   6,   7],
       [  9,  10,  11]])

In [8]:
# changing element at [0,0] of arr_copy will make no change in value of element [0,0] in arr
print("Before changing arr_copy")
print(f"arr_copy[0,0] = {arr_copy[0,0]}")
print(f"arr[0,0] = {arr[0,0]}")
print("="*30)
print("After changing arr_copy")
arr_copy[0,0] = 1
print(f"arr_copy[0,0] = {arr_copy[0,0]}")
print(f"arr[0,0] = {arr[0,0]}")

Before changing arr_copy
arr_copy[0,0] = 100
arr[0,0] = 100
After changing arr_copy
arr_copy[0,0] = 1
arr[0,0] = 100
