In [1]:
import numpy as np

In [2]:
# generating 1D array using arange
arr_org = np.arange(1, 25)
arr_org

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [3]:
# Details of orginal array
print(f"Elements in arr_org => {arr_org.size}")
print(f"Shape of arr_org => {arr_org.shape}")
print(f"Dimension in arr_org => {arr_org.ndim}")

Elements in arr_org => 24
Shape of arr_org => (24,)
Dimension in arr_org => 1


In [4]:
# Using reshape() as numpy function - 1D array into 2D array
arr_2d = np.reshape(arr_org, (4, 6))
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [5]:
# Details of 2D array created from original array
print(f"Elements in arr_2d => {arr_2d.size}")
print(f"Shape of arr_2d => {arr_2d.shape}")
print(f"Dimension in arr_2d => {arr_2d.ndim}")

Elements in arr_2d => 24
Shape of arr_2d => (4, 6)
Dimension in arr_2d => 2


In [6]:
# Using reshape() as numpy function - 2D array into 3D array
arr_3d = np.reshape(arr_2d, (2, 3, 4))
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [7]:
# Using reshape() as numpy function - 3D array into 1D array
arr_1d = np.reshape(arr_3d, (24,))
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [8]:
# Since arr_1d is view of arr_3d which is view of arr_2d, which is view of arr_1d, which again is view of arr_org, 
# so if we change the 1st element of arr_1d, change must also reflect in arr_org.
print(f"Present Value")
print(f"arr_1d[0] => {arr_1d[0]}  |  arr_org[0] => {arr_org[0]}")

arr_1d[0] = 0

print(f"After arr_1d[0] = 0")
print(f"arr_1d[0] => {arr_1d[0]}  |  arr_org[0] => {arr_org[0]}")

Present Value
arr_1d[0] => 1  |  arr_org[0] => 1
After arr_1d[0] = 0
arr_1d[0] => 0  |  arr_org[0] => 0


In [9]:
# Using order argument in reshape as numpy function
arr_3d_C = np.reshape(arr_org, (2, 3, 4), order="C")
print(f"arr_3d with order as C (columns-like)\n{arr_3d_C}")

print("\n", "="*30, "\n")

arr_3d_F = np.reshape(arr_org, (2, 3, 4), order="f")
print(f"arr_3d with order as F (Fortan-like)\n{arr_3d_F}")

arr_3d with order as C (columns-like)
[[[ 0  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


arr_3d with order as F (Fortan-like)
[[[ 0  7 13 19]
  [ 3  9 15 21]
  [ 5 11 17 23]]

 [[ 2  8 14 20]
  [ 4 10 16 22]
  [ 6 12 18 24]]]


In [10]:
# Using order argument in reshape as numpy function
arr_2d_C = np.reshape(arr_org, (4, 6), order="C")
print(f"arr_2d with order as C (columns-like)\n{arr_2d_C}")

print("\n", "="*30, "\n")

arr_2d_F = np.reshape(arr_org, (4, 6), order="f")
print(f"arr_2d with order as F (Fortan-like)\n{arr_2d_F}")

arr_2d with order as C (columns-like)
[[ 0  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


arr_2d with order as F (Fortan-like)
[[ 0  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]
 [ 4  8 12 16 20 24]]


In [11]:
# Using reshape() as array function - 1D array into 3D array
arr_3d = arr_org.reshape([2, 3, 4])
arr_3d

array([[[ 0,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [12]:
# using argument 'order' with reshape() as numpy array function
arr_2d_C = arr_org.reshape([4, 6], order="C")
print(f"arr_2d with order as C (columns-like)\n{arr_2d_C}")

print("\n", "="*30, "\n")

arr_2d_F = arr_org.reshape([4, 6], order="f")
print(f"arr_2d with order as F (Fortan-like)\n{arr_2d_F}")

arr_2d with order as C (columns-like)
[[ 0  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


arr_2d with order as F (Fortan-like)
[[ 0  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]
 [ 4  8 12 16 20 24]]


In [13]:
# using -1
arr_2d_1 = arr_org.reshape([3,-1])
arr_2d_1
# arr_2d_1.shape

array([[ 0,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [14]:
# using -1
arr_3d_1 = np.arange(1,100).reshape([3,3,-1])
print(arr_3d_1)
print()
print("Value that substituted -1 => ", arr_3d_1.shape[2])

[[[ 1  2  3  4  5  6  7  8  9 10 11]
  [12 13 14 15 16 17 18 19 20 21 22]
  [23 24 25 26 27 28 29 30 31 32 33]]

 [[34 35 36 37 38 39 40 41 42 43 44]
  [45 46 47 48 49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62 63 64 65 66]]

 [[67 68 69 70 71 72 73 74 75 76 77]
  [78 79 80 81 82 83 84 85 86 87 88]
  [89 90 91 92 93 94 95 96 97 98 99]]]

Value that substituted -1 =>  11
