In [1]:
import numpy as np

In [2]:
# Retrun array with element > 10
arr = np.random.randint(0,20,10).reshape(2,5)
print(arr)
print(arr>10)

[[ 4  0 17 10  8]
 [14  1  2  0 18]]
[[False False  True False False]
 [ True False False False  True]]


In [3]:
# Retrun array with element > 10 and < 15
arr = np.random.randint(0,20,10).reshape(2,5)
print(arr)
print(((arr > 10) & (arr < 15)))

[[ 1  1 14 16 17]
 [15 14  1  1  9]]
[[False False  True False False]
 [False  True False False False]]


In [4]:
# replace element which satisfy condition with 100
arr = np.random.randint(0,20,10).reshape(2,5)
print(arr)
arr[arr>10] = 100
print(arr)

[[13  2  7  5 18]
 [ 0 16  6  3  0]]
[[100   2   7   5 100]
 [  0 100   6   3   0]]


In [5]:
# replace element which fails condition with 0
arr = np.random.randint(0,20,10).reshape(2,5)
print(arr)
print(f"(arr>10):\n{arr>10}")
a= arr[~(arr>10)] = 0
print(f"arr[~(arr>10)] = 0:\n{a}")
print(arr)

[[ 5  4 16 17  6]
 [17  0 16  0 12]]
(arr>10):
[[False False  True  True False]
 [ True False  True False  True]]
arr[~(arr>10)] = 0:
0
[[ 0  0 16 17  0]
 [17  0 16  0 12]]


# any()

In [6]:
# if there is any non-0 element in array
arr = np.random.randint(0,2,4).reshape(2,2)
filt = arr.any()
print(arr)
print(filt)

[[0 1]
 [0 1]]
True


In [7]:
# if there is any element is greater then 1
arr = np.random.randint(0,2,4).reshape(2,2)
filt = np.any(arr>1)
print(arr)
print(filt)

[[0 0]
 [1 1]]
False


In [8]:
# if there is any non-0 element in row
arr = np.random.randint(0,2,4).reshape(2,2)
filt = arr.any(axis=1)
print(arr)
print(filt)

[[0 1]
 [0 0]]
[ True False]


In [9]:
# if there is any non-0 element in columns
arr = np.random.randint(0,2,4).reshape(2,2)
filt = arr.any(axis=0)
print(arr)
print(filt)

[[0 1]
 [1 1]]
[ True  True]


In [10]:
# if there is any element>=1 in columns
arr = np.random.randint(0,2,4).reshape(2,2)
filt = np.any(arr>=1, axis=0)
print(arr)
print(filt)

[[0 1]
 [1 0]]
[ True  True]


In [11]:
# if there is any element>=1 in rows
arr = np.random.randint(0,2,4).reshape(2,2)
filt = np.any(arr>=1, axis=1)
print(arr)
print(filt)

[[1 1]
 [0 0]]
[ True False]


# all()

In [12]:
# if there all elements are non-0 in array
arr = np.random.randint(0,2,4).reshape(2,2)
filt = arr.all()
print(arr)
print(filt)

[[1 0]
 [1 0]]
False


In [13]:
# if all elements are non-0 in rows
arr = np.random.randint(0,2,4).reshape(2,2)
filt = arr.all(axis=1)
print(arr)
print(filt)

[[1 1]
 [0 0]]
[ True False]


In [14]:
# if all elements are non-0 in columns
arr = np.random.randint(0,2,4).reshape(2,2)
filt = arr.all(axis=0)
print(arr)
print(filt)
print(~filt)

[[0 1]
 [1 0]]
[False False]
[ True  True]


In [15]:
# if all elements in array is >= 1
arr = np.random.randint(0,2,4).reshape(2,2)
filt = np.all(arr>=1)
print(arr)
print(filt)

[[0 1]
 [1 0]]
False


In [16]:
# if all elements in each columns is >= 1
arr = np.random.randint(0,2,4).reshape(2,2)
filt = np.all(arr>=1, axis=0)
print(arr)
print(filt)

[[0 1]
 [0 0]]
[False False]


In [17]:
# if all elements in each rows is >= 1
arr = np.random.randint(0,2,4).reshape(2,2)
filt = np.all(arr>=1, axis=1)
print(arr)
print(filt)

[[1 0]
 [0 1]]
[False False]


# isnan()

In [18]:
# checking if element is missng value
arr = np.array([0,1,2,3,np.nan, 5,6,7, np.nan]).reshape(3,3)
filt = np.isnan(arr)
print(arr)
print(filt)

[[ 0.  1.  2.]
 [ 3. nan  5.]
 [ 6.  7. nan]]
[[False False False]
 [False  True False]
 [False False  True]]


# isinf()

In [19]:
# checking if element is infity
arr = np.array([0,1,2,3,np.inf, 5,6,7, -np.inf]).reshape(3,3)
filt = np.isinf(arr)
print(arr)
print(filt)

[[  0.   1.   2.]
 [  3.  inf   5.]
 [  6.   7. -inf]]
[[False False False]
 [False  True False]
 [False False  True]]


In [20]:
# checking if element is negative infity
arr = np.array([0,1,2,3,np.inf, 5,6,7, -np.inf]).reshape(3,3)
filt = (arr == -np.inf)
print(arr)
print(filt)

[[  0.   1.   2.]
 [  3.  inf   5.]
 [  6.   7. -inf]]
[[False False False]
 [False False False]
 [False False  True]]


# count_nonzero()

In [21]:
# count_nonzero() => counts totoal non-zero elements in array
arr = np.random.randint(0,3,10).reshape(2,5)
print((arr))
np.count_nonzero(arr)

[[1 1 1 1 1]
 [0 2 0 0 0]]


6

In [22]:
# count_nonzero() => counts elements that satisfy condition and is faster then sum()
arr = np.random.randint(0,20,10).reshape(2,5)
filt = arr>10
print(arr)
print(filt)
np.count_nonzero(filt)  # this is similar to np.count_nonzero(arr>10)

[[ 6 15  5  7  9]
 [ 6 12 14  2 18]]
[[False  True False False False]
 [False  True  True False  True]]


4

In [23]:
# using count_nonzero to count true elements row wise
arr = np.random.randint(0,20,24).reshape(4,6)
print(arr)
np.count_nonzero(arr>10, axis=1)

[[ 7 11 15 13  3  9]
 [14  9 12  7  7  5]
 [ 7  1 11  3 16 18]
 [ 4  1  0  6 16 11]]


array([3, 2, 3, 2], dtype=int32)

In [24]:
# using count_nonzero to count true elements column wise
arr = np.random.randint(0,20,24).reshape(4,6)
print(arr)
np.count_nonzero(arr>10, axis=0)

[[ 7 13 19  8  9 15]
 [10  8  1 13 12  7]
 [ 3 10 18 16  2 16]
 [18 16 15  4  5 13]]


array([1, 2, 3, 2, 1, 3], dtype=int32)

# where()

In [25]:
# using where() function to get same result.
arr = np.random.randint(0,20,10).reshape(2,5)
filt = np.where(arr>10)
print(arr)
print(filt)

[[ 3 17  4 13 18]
 [18  6  5 14  4]]
(array([0, 0, 0, 1, 1], dtype=int32), array([1, 3, 4, 0, 3], dtype=int32))


In [26]:
# using where() function to get same result.
arr = np.random.randint(0,20,10).reshape(2,5)
filt = np.where(arr>10, True, False)
print(arr)
print(filt)

[[10  1  5  4  6]
 [ 1  4 17  9  2]]
[[False False False False False]
 [False False  True False False]]


In [27]:
# Change element that are not > 10 to 0
arr = np.random.randint(0,20,10).reshape(2,5)
filt = np.where(arr>10, arr, 0)
print(arr)
print(filt)

[[ 3  0 10  3  6]
 [ 6  8 12  3  1]]
[[ 0  0  0  0  0]
 [ 0  0 12  0  0]]


In [28]:
# Change element that are not > 10 to 0 else make them 1
arr = np.random.randint(0,20,10).reshape(2,5)
filt = np.where(arr>10, 1, 0)
print(arr)
print(filt)

[[14 14 17  3  0]
 [18  5 16 18 14]]
[[1 1 1 0 0]
 [1 0 1 1 1]]


In [29]:
# number of non-zero elemets
arr = np.random.randint(0,20,10).reshape(2,5)
filt = np.where(~(arr==0), 1, 0)
print(arr)
print(filt)
print("Sum: ", filt.sum())

[[ 6  0 16 13 13]
 [ 9  5 16  7 17]]
[[1 0 1 1 1]
 [1 1 1 1 1]]
Sum:  9


In [32]:
# number of zero elemets
arr = np.random.randint(0,20,10).reshape(2,5)
filt = np.where(arr==0, 1, 0)
print(arr)
print(filt)
print("Sum: ", filt.sum())

[[16  8 15 13 15]
 [16 16  8  0 16]]
[[0 0 0 0 0]
 [0 0 0 1 0]]
Sum:  1


In [31]:
# indices of element that satisfy the condition
arr = np.random.randint(0,20,10).reshape(2,5)
filt = np.where(arr>10)
print(arr)
print(filt)
print(list(zip(*filt)))

[[17 10  7  2  2]
 [ 6  4  4  7  3]]
(array([0], dtype=int32), array([0], dtype=int32))
[(0, 0)]
